// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (user_name, password_hash, role, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, user_name, password_hash, role, created_at, created_by
`

type CreateAdminParams struct {
	UserName     string        `json:"user_name"`
	PasswordHash string        `json:"password_hash"`
	Role         AdminRole     `json:"role"`
	CreatedBy    sql.NullInt32 `json:"created_by"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, createAdmin,
		arg.UserName,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedBy,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createSuperAdmin = `-- name: CreateSuperAdmin :one
INSERT INTO admins (user_name, password_hash, role, created_by)
VALUES ($1, $2, 'super-admin', $3)
RETURNING id, user_name, password_hash, role, created_at, created_by
`

type CreateSuperAdminParams struct {
	UserName     string        `json:"user_name"`
	PasswordHash string        `json:"password_hash"`
	CreatedBy    sql.NullInt32 `json:"created_by"`
}

func (q *Queries) CreateSuperAdmin(ctx context.Context, arg CreateSuperAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, createSuperAdmin, arg.UserName, arg.PasswordHash, arg.CreatedBy)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE
FROM admins
WHERE id = $1
`

func (q *Queries) DeleteAdmin(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAdmin, id)
	return err
}

const getAdminByID = `-- name: GetAdminByID :one

SELECT id, user_name, password_hash, role, created_at, created_by
FROM admins
WHERE id = $1
LIMIT 1
`

// TODO: убрать возвращение полных данных из БД, возвращать только id при создании админа
func (q *Queries) GetAdminByID(ctx context.Context, id int32) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, user_name, password_hash, role, created_at, created_by
FROM admins
WHERE user_name = $1
LIMIT 1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, userName string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByUsername, userName)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, user_name, password_hash, role, created_at, created_by
FROM admins
ORDER BY user_name
`

func (q *Queries) ListAdmins(ctx context.Context) ([]Admin, error) {
	rows, err := q.db.QueryContext(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Admin
	for rows.Next() {
		var i Admin
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
