// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_types.sql

package sqlc

import (
	"context"
)

const createEventType = `-- name: CreateEventType :one
INSERT INTO event_types (name, color)
VALUES ($1, $2)
RETURNING id, name, color
`

type CreateEventTypeParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

func (q *Queries) CreateEventType(ctx context.Context, arg CreateEventTypeParams) (EventType, error) {
	row := q.db.QueryRowContext(ctx, createEventType, arg.Name, arg.Color)
	var i EventType
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const deleteEventType = `-- name: DeleteEventType :exec
DELETE
FROM event_types
WHERE id = $1
`

func (q *Queries) DeleteEventType(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEventType, id)
	return err
}

const getEventTypeByID = `-- name: GetEventTypeByID :one
SELECT id, name, color
FROM event_types
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEventTypeByID(ctx context.Context, id int32) (EventType, error) {
	row := q.db.QueryRowContext(ctx, getEventTypeByID, id)
	var i EventType
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const getEventTypeByName = `-- name: GetEventTypeByName :one
SELECT id, name, color
FROM event_types
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetEventTypeByName(ctx context.Context, name string) (EventType, error) {
	row := q.db.QueryRowContext(ctx, getEventTypeByName, name)
	var i EventType
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const listEventTypes = `-- name: ListEventTypes :many
SELECT id, name, color
FROM event_types
ORDER BY name
`

func (q *Queries) ListEventTypes(ctx context.Context) ([]EventType, error) {
	rows, err := q.db.QueryContext(ctx, listEventTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventType
	for rows.Next() {
		var i EventType
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventType = `-- name: UpdateEventType :exec
UPDATE event_types
SET name  = $2,
    color = $3
WHERE id = $1
`

type UpdateEventTypeParams struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
}

func (q *Queries) UpdateEventType(ctx context.Context, arg UpdateEventTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateEventType, arg.ID, arg.Name, arg.Color)
	return err
}
