// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: site_requests.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const approveSiteRequest = `-- name: ApproveSiteRequest :exec
UPDATE site_requests
SET status      = 'approved',
    reviewed_at = NOW(),
    reviewed_by = $2
WHERE id = $1
`

type ApproveSiteRequestParams struct {
	ID         int32         `json:"id"`
	ReviewedBy sql.NullInt32 `json:"reviewed_by"`
}

func (q *Queries) ApproveSiteRequest(ctx context.Context, arg ApproveSiteRequestParams) error {
	_, err := q.db.ExecContext(ctx, approveSiteRequest, arg.ID, arg.ReviewedBy)
	return err
}

const countSiteRequestsByStatus = `-- name: CountSiteRequestsByStatus :one
SELECT COUNT(*)
FROM site_requests
WHERE status = $1
`

func (q *Queries) CountSiteRequestsByStatus(ctx context.Context, status RequestStatus) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSiteRequestsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSiteRequest = `-- name: CreateSiteRequest :one
INSERT INTO site_requests (user_email, user_name, site_title, site_description, location, event_date, event_type_id,
                            archive_path, extracted_path, preview_image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_email, user_name, site_title, site_description, location, event_date, event_type_id, archive_path, extracted_path, preview_image_url, status, rejection_reason, submitted_at, reviewed_at, reviewed_by
`

type CreateSiteRequestParams struct {
	UserEmail       string         `json:"user_email"`
	UserName        string         `json:"user_name"`
	SiteTitle       string         `json:"site_title"`
	SiteDescription sql.NullString `json:"site_description"`
	Location        interface{}    `json:"location"`
	EventDate       time.Time      `json:"event_date"`
	EventTypeID     int32          `json:"event_type_id"`
	ArchivePath     sql.NullString `json:"archive_path"`
	ExtractedPath   sql.NullString `json:"extracted_path"`
	PreviewImageUrl sql.NullString `json:"preview_image_url"`
}

func (q *Queries) CreateSiteRequest(ctx context.Context, arg CreateSiteRequestParams) (SiteRequest, error) {
	row := q.db.QueryRowContext(ctx, createSiteRequest,
		arg.UserEmail,
		arg.UserName,
		arg.SiteTitle,
		arg.SiteDescription,
		arg.Location,
		arg.EventDate,
		arg.EventTypeID,
		arg.ArchivePath,
		arg.ExtractedPath,
		arg.PreviewImageUrl,
	)
	var i SiteRequest
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.UserName,
		&i.SiteTitle,
		&i.SiteDescription,
		&i.Location,
		&i.EventDate,
		&i.EventTypeID,
		&i.ArchivePath,
		&i.ExtractedPath,
		&i.PreviewImageUrl,
		&i.Status,
		&i.RejectionReason,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
	)
	return i, err
}

const deleteSiteRequest = `-- name: DeleteSiteRequest :exec
DELETE
FROM site_requests
WHERE id = $1
`

func (q *Queries) DeleteSiteRequest(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSiteRequest, id)
	return err
}

const getPendingSiteRequests = `-- name: GetPendingSiteRequests :many
SELECT id, user_email, user_name, site_title, site_description, location, event_date, event_type_id, archive_path, extracted_path, preview_image_url, status, rejection_reason, submitted_at, reviewed_at, reviewed_by
FROM site_requests
WHERE status = 'pending'
ORDER BY submitted_at ASC
`

func (q *Queries) GetPendingSiteRequests(ctx context.Context) ([]SiteRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPendingSiteRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteRequest
	for rows.Next() {
		var i SiteRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.UserName,
			&i.SiteTitle,
			&i.SiteDescription,
			&i.Location,
			&i.EventDate,
			&i.EventTypeID,
			&i.ArchivePath,
			&i.ExtractedPath,
			&i.PreviewImageUrl,
			&i.Status,
			&i.RejectionReason,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSiteRequestByID = `-- name: GetSiteRequestByID :one
SELECT id, user_email, user_name, site_title, site_description, location, event_date, event_type_id, archive_path, extracted_path, preview_image_url, status, rejection_reason, submitted_at, reviewed_at, reviewed_by
FROM site_requests
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSiteRequestByID(ctx context.Context, id int32) (SiteRequest, error) {
	row := q.db.QueryRowContext(ctx, getSiteRequestByID, id)
	var i SiteRequest
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.UserName,
		&i.SiteTitle,
		&i.SiteDescription,
		&i.Location,
		&i.EventDate,
		&i.EventTypeID,
		&i.ArchivePath,
		&i.ExtractedPath,
		&i.PreviewImageUrl,
		&i.Status,
		&i.RejectionReason,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
	)
	return i, err
}

const getSiteRequestsWithinRadius = `-- name: GetSiteRequestsWithinRadius :many
SELECT id, user_email, user_name, site_title, site_description, location, event_date, event_type_id, archive_path, extracted_path, preview_image_url, status, rejection_reason, submitted_at, reviewed_at, reviewed_by,
       ST_Distance(location, ST_SetSRID(ST_MakePoint($1, $2), 4326)) as distance
FROM site_requests
WHERE ST_DWithin(location, ST_SetSRID(ST_MakePoint($1, $2), 4326), $3)
ORDER BY distance
`

type GetSiteRequestsWithinRadiusParams struct {
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	StDwithin     interface{} `json:"st_dwithin"`
}

type GetSiteRequestsWithinRadiusRow struct {
	ID              int32          `json:"id"`
	UserEmail       string         `json:"user_email"`
	UserName        string         `json:"user_name"`
	SiteTitle       string         `json:"site_title"`
	SiteDescription sql.NullString `json:"site_description"`
	Location        interface{}    `json:"location"`
	EventDate       time.Time      `json:"event_date"`
	EventTypeID     int32          `json:"event_type_id"`
	ArchivePath     sql.NullString `json:"archive_path"`
	ExtractedPath   sql.NullString `json:"extracted_path"`
	PreviewImageUrl sql.NullString `json:"preview_image_url"`
	Status          RequestStatus  `json:"status"`
	RejectionReason sql.NullString `json:"rejection_reason"`
	SubmittedAt     sql.NullTime   `json:"submitted_at"`
	ReviewedAt      sql.NullTime   `json:"reviewed_at"`
	ReviewedBy      sql.NullInt32  `json:"reviewed_by"`
	Distance        interface{}    `json:"distance"`
}

func (q *Queries) GetSiteRequestsWithinRadius(ctx context.Context, arg GetSiteRequestsWithinRadiusParams) ([]GetSiteRequestsWithinRadiusRow, error) {
	rows, err := q.db.QueryContext(ctx, getSiteRequestsWithinRadius, arg.StMakepoint, arg.StMakepoint_2, arg.StDwithin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSiteRequestsWithinRadiusRow
	for rows.Next() {
		var i GetSiteRequestsWithinRadiusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.UserName,
			&i.SiteTitle,
			&i.SiteDescription,
			&i.Location,
			&i.EventDate,
			&i.EventTypeID,
			&i.ArchivePath,
			&i.ExtractedPath,
			&i.PreviewImageUrl,
			&i.Status,
			&i.RejectionReason,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteRequests = `-- name: ListSiteRequests :many
SELECT id, user_email, user_name, site_title, site_description, location, event_date, event_type_id, archive_path, extracted_path, preview_image_url, status, rejection_reason, submitted_at, reviewed_at, reviewed_by
FROM site_requests
ORDER BY submitted_at DESC
`

func (q *Queries) ListSiteRequests(ctx context.Context) ([]SiteRequest, error) {
	rows, err := q.db.QueryContext(ctx, listSiteRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteRequest
	for rows.Next() {
		var i SiteRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.UserName,
			&i.SiteTitle,
			&i.SiteDescription,
			&i.Location,
			&i.EventDate,
			&i.EventTypeID,
			&i.ArchivePath,
			&i.ExtractedPath,
			&i.PreviewImageUrl,
			&i.Status,
			&i.RejectionReason,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteRequestsByEmail = `-- name: ListSiteRequestsByEmail :many
SELECT id, user_email, user_name, site_title, site_description, location, event_date, event_type_id, archive_path, extracted_path, preview_image_url, status, rejection_reason, submitted_at, reviewed_at, reviewed_by
FROM site_requests
WHERE user_email = $1
ORDER BY submitted_at DESC
`

func (q *Queries) ListSiteRequestsByEmail(ctx context.Context, userEmail string) ([]SiteRequest, error) {
	rows, err := q.db.QueryContext(ctx, listSiteRequestsByEmail, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteRequest
	for rows.Next() {
		var i SiteRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.UserName,
			&i.SiteTitle,
			&i.SiteDescription,
			&i.Location,
			&i.EventDate,
			&i.EventTypeID,
			&i.ArchivePath,
			&i.ExtractedPath,
			&i.PreviewImageUrl,
			&i.Status,
			&i.RejectionReason,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteRequestsByEventType = `-- name: ListSiteRequestsByEventType :many
SELECT id, user_email, user_name, site_title, site_description, location, event_date, event_type_id, archive_path, extracted_path, preview_image_url, status, rejection_reason, submitted_at, reviewed_at, reviewed_by
FROM site_requests
WHERE event_type_id = $1
ORDER BY submitted_at DESC
`

func (q *Queries) ListSiteRequestsByEventType(ctx context.Context, eventTypeID int32) ([]SiteRequest, error) {
	rows, err := q.db.QueryContext(ctx, listSiteRequestsByEventType, eventTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteRequest
	for rows.Next() {
		var i SiteRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.UserName,
			&i.SiteTitle,
			&i.SiteDescription,
			&i.Location,
			&i.EventDate,
			&i.EventTypeID,
			&i.ArchivePath,
			&i.ExtractedPath,
			&i.PreviewImageUrl,
			&i.Status,
			&i.RejectionReason,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteRequestsByStatus = `-- name: ListSiteRequestsByStatus :many
SELECT id, user_email, user_name, site_title, site_description, location, event_date, event_type_id, archive_path, extracted_path, preview_image_url, status, rejection_reason, submitted_at, reviewed_at, reviewed_by
FROM site_requests
WHERE status = $1
ORDER BY submitted_at DESC
`

func (q *Queries) ListSiteRequestsByStatus(ctx context.Context, status RequestStatus) ([]SiteRequest, error) {
	rows, err := q.db.QueryContext(ctx, listSiteRequestsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteRequest
	for rows.Next() {
		var i SiteRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.UserName,
			&i.SiteTitle,
			&i.SiteDescription,
			&i.Location,
			&i.EventDate,
			&i.EventTypeID,
			&i.ArchivePath,
			&i.ExtractedPath,
			&i.PreviewImageUrl,
			&i.Status,
			&i.RejectionReason,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectSiteRequest = `-- name: RejectSiteRequest :exec
UPDATE site_requests
SET status           = 'rejected',
    rejection_reason = $2,
    reviewed_at      = NOW(),
    reviewed_by      = $3
WHERE id = $1
`

type RejectSiteRequestParams struct {
	ID              int32          `json:"id"`
	RejectionReason sql.NullString `json:"rejection_reason"`
	ReviewedBy      sql.NullInt32  `json:"reviewed_by"`
}

func (q *Queries) RejectSiteRequest(ctx context.Context, arg RejectSiteRequestParams) error {
	_, err := q.db.ExecContext(ctx, rejectSiteRequest, arg.ID, arg.RejectionReason, arg.ReviewedBy)
	return err
}

const updateSiteRequest = `-- name: UpdateSiteRequest :exec
UPDATE site_requests
SET user_email        = $2,
    user_name         = $3,
    site_title        = $4,
    site_description  = $5,
    location          = $6,
    event_date        = $7,
    event_type_id     = $8,
    archive_path      = $9,
    extracted_path    = $10,
    preview_image_url = $11
WHERE id = $1
`

type UpdateSiteRequestParams struct {
	ID              int32          `json:"id"`
	UserEmail       string         `json:"user_email"`
	UserName        string         `json:"user_name"`
	SiteTitle       string         `json:"site_title"`
	SiteDescription sql.NullString `json:"site_description"`
	Location        interface{}    `json:"location"`
	EventDate       time.Time      `json:"event_date"`
	EventTypeID     int32          `json:"event_type_id"`
	ArchivePath     sql.NullString `json:"archive_path"`
	ExtractedPath   sql.NullString `json:"extracted_path"`
	PreviewImageUrl sql.NullString `json:"preview_image_url"`
}

func (q *Queries) UpdateSiteRequest(ctx context.Context, arg UpdateSiteRequestParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteRequest,
		arg.ID,
		arg.UserEmail,
		arg.UserName,
		arg.SiteTitle,
		arg.SiteDescription,
		arg.Location,
		arg.EventDate,
		arg.EventTypeID,
		arg.ArchivePath,
		arg.ExtractedPath,
		arg.PreviewImageUrl,
	)
	return err
}

const updateSiteRequestStatus = `-- name: UpdateSiteRequestStatus :exec
UPDATE site_requests
SET status          = $2,
    rejection_reason = $3,
    reviewed_at     = $4,
    reviewed_by     = $5
WHERE id = $1
`

type UpdateSiteRequestStatusParams struct {
	ID              int32          `json:"id"`
	Status          RequestStatus  `json:"status"`
	RejectionReason sql.NullString `json:"rejection_reason"`
	ReviewedAt      sql.NullTime   `json:"reviewed_at"`
	ReviewedBy      sql.NullInt32  `json:"reviewed_by"`
}

func (q *Queries) UpdateSiteRequestStatus(ctx context.Context, arg UpdateSiteRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteRequestStatus,
		arg.ID,
		arg.Status,
		arg.RejectionReason,
		arg.ReviewedAt,
		arg.ReviewedBy,
	)
	return err
}
